[theme]
base="dark"                  # 기본 모드 ("light" 또는 "dark")
primaryColor="#708090"        # 버튼, 선택박스 등 포인트 강조 색상
backgroundColor="#2b374a"     # 메인 화면 배경색
secondaryBackgroundColor="#3c4d69" # 사이드바 및 위젯 배경색
textColor="#caddfa"           # 글자 색상
